/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veto;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AKRAMEE
 */
public class animalsPanel extends javax.swing.JPanel {

    /**
     * Creates new form animalsPanel
     */
    public animalsPanel() {
        initComponents();
        jButton_Ajouter.setEnabled(false);
        jButton_save.setEnabled(false);
        resetClientInfo();
        
        ListSelectionModel model=jTable_animal.getSelectionModel();
        model.addListSelectionListener(new ListSelectionListener (){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                //To change body of generated methods, choose Tools | Templates.
              if( ! model.isSelectionEmpty()){ 
                int row= model.getMinSelectionIndex();
                DefaultTableModel m=(DefaultTableModel) jTable_animal.getModel();
              selectedAnimal= Integer.parseInt( m.getValueAt(row, 0).toString());
                  try {
                      ResultSet  rs= getAnimal(selectedAnimal,"idAnimal");
                      selectedClient= rs.getInt("proprietaire");
                      
                      showClientInfo(selectedClient);
                      
                      jText_nom.setText(rs.getString("nomAnimal"));
                      jText_race.setText(rs.getString("raceAnimal"));
                      jText_espece.setText(rs.getString("especeAnimal"));
                      jText_car.setText(rs.getString("carAnimal"));
                      jText_poids.setText(rs.getString("poids"));
                      jCombo_unite.setSelectedItem(rs.getString("uniteMesure"));
                      jButton_save.setEnabled(true);
                      
                      rs.close();
                      
                  } catch (SQLException ex) {
                      Logger.getLogger(animalsPanel.class.getName()).log(Level.SEVERE, null, ex);
                  }
               
              
              }
            }
            
        });
        
        try {
            showAnimal(jTable_animal);
            clientPanel.showClientInCombo(jCombo_client);
            
        } catch (SQLException ex) {
            Logger.getLogger(animalsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_sexe = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jCombo_client = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jText_nom = new javax.swing.JTextField();
        jText_race = new javax.swing.JTextField();
        jText_espece = new javax.swing.JTextField();
        jText_poids = new javax.swing.JTextField();
        jCombo_unite = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jText_car = new javax.swing.JTextArea();
        jButton_Ajouter = new javax.swing.JButton();
        jButton_save = new javax.swing.JButton();
        jRadio_M = new javax.swing.JRadioButton();
        jRadio_F = new javax.swing.JRadioButton();
        jLabel_notes = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_animal = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_name = new javax.swing.JLabel();
        jLabelm = new javax.swing.JLabel();
        jLabela = new javax.swing.JLabel();
        jLabel_mobile = new javax.swing.JLabel();
        jLabel_adr = new javax.swing.JLabel();
        jPanel_annuler = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Proprietaire :");

        jCombo_client.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jCombo_client.setMaximumRowCount(15);
        jCombo_client.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectioner le proprietaire" }));
        jCombo_client.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCombo_clientItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Animal : ");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Nom");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Espèce ");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Race");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Sexe");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Poids");

        jText_nom.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jText_nom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jText_nomFocusLost(evt);
            }
        });
        jText_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_nomActionPerformed(evt);
            }
        });

        jText_race.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jText_race.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_raceActionPerformed(evt);
            }
        });

        jText_espece.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jText_espece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_especeActionPerformed(evt);
            }
        });

        jText_poids.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jCombo_unite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gr", "Kg" }));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Caracteristique ");

        jText_car.setColumns(20);
        jText_car.setRows(5);
        jScrollPane1.setViewportView(jText_car);

        jButton_Ajouter.setText("Ajouter ");
        jButton_Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AjouterActionPerformed(evt);
            }
        });

        jButton_save.setText("Sauvgarder modification");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });

        buttonGroup_sexe.add(jRadio_M);
        jRadio_M.setText("Male");
        jRadio_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_MActionPerformed(evt);
            }
        });

        buttonGroup_sexe.add(jRadio_F);
        jRadio_F.setText("Female");

        jLabel_notes.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel_notes.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_nom)
                            .addComponent(jText_espece)
                            .addComponent(jText_race)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadio_F)
                                .addGap(43, 43, 43)
                                .addComponent(jRadio_M)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jText_poids)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCombo_unite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCombo_client, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_notes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCombo_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jText_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jText_espece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jText_race, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRadio_M)
                    .addComponent(jRadio_F))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jText_poids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombo_unite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_save)
                    .addComponent(jButton_Ajouter))
                .addGap(18, 18, 18)
                .addComponent(jLabel_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));

        jTable_animal.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTable_animal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nom", "Espece", "Race", "Sexe", "Poids"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_animal.setRowHeight(22);
        jTable_animal.setRowMargin(2);
        jTable_animal.setSelectionBackground(new java.awt.Color(0, 206, 209));
        jScrollPane2.setViewportView(jTable_animal);
        if (jTable_animal.getColumnModel().getColumnCount() > 0) {
            jTable_animal.getColumnModel().getColumn(0).setMaxWidth(45);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Proprietaire : ");

        jLabel_name.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel_name.setText("Amar Neche");

        jLabelm.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelm.setText("Mobile : ");

        jLabela.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabela.setText("Adresse :");

        jLabel_mobile.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel_mobile.setText("067337481");

        jLabel_adr.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel_adr.setText("addreszs");

        jPanel_annuler.setBackground(new java.awt.Color(0, 206, 209));
        jPanel_annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_annulerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_annulerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_annulerMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Close Window_18px.png"))); // NOI18N
        jLabel10.setText("Supprimer Animal");

        javax.swing.GroupLayout jPanel_annulerLayout = new javax.swing.GroupLayout(jPanel_annuler);
        jPanel_annuler.setLayout(jPanel_annulerLayout);
        jPanel_annulerLayout.setHorizontalGroup(
            jPanel_annulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_annulerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_annulerLayout.setVerticalGroup(
            jPanel_annulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_annulerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_adr, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(371, 405, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_name))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelm)
                            .addComponent(jLabel_mobile)))
                    .addComponent(jPanel_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabela)
                    .addComponent(jLabel_adr))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jText_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_nomActionPerformed

    private void jText_raceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_raceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_raceActionPerformed

    private void jText_especeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_especeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_especeActionPerformed

    private void jButton_AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AjouterActionPerformed
        // TODO add your handling code here:
        String nomAnimal= jText_nom.getText();
        String espece= jText_espece.getText();
        String race = jText_race.getText();
        String sexe = null ;
        String poids =jText_poids.getText();
        String unite =(String) jCombo_unite.getSelectedItem();
        
        String car=jText_car.getText();
        
        
        
        if(  jRadio_F.isSelected()){
          sexe="Female";
      }
        else if(jRadio_M.isSelected()) sexe="Male";
        if(selectedClient==0)  {
            jLabel_notes.setText("veuillez selectionner le proprietaire"); 
            jLabel_name.setText("");
            jLabel_adr.setText("");
            jLabel_mobile.setText("");
            jButton_Ajouter.setEnabled(false); }
        else {
            
        jButton_Ajouter.setEnabled(true);
        
        String sql="insert into animals(proprietaire, nomAnimal,sexeAnimal,raceAnimal,especeAnimal,carAnimal,poids,uniteMesure )"
                + "values("
                +selectedClient+","
                +"'"+nomAnimal +"',"
                +"'"+sexe+ "',"
                +"'"+ race+"',"
                +"'"+ espece+"',"
                +"'"+car+"',"
                +"'"+ poids+"',"
                +"'"+ unite+"')";
        
        
                
        try {
            Connection connect =Main.getConnection(Main.jdbc);
            
            Statement stmt =connect.createStatement();
            
           boolean execute =stmt.execute(sql);
            if(!execute || execute ){ 
                jLabel_notes.setText("Animal added");
                selectedClient=0;
                showAnimal(jTable_animal);
                
            }
            stmt.close();
            connect.close();
        } catch (SQLException ex) {
            Logger.getLogger(animalsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
               
        
        }
        
    }//GEN-LAST:event_jButton_AjouterActionPerformed

    private void jRadio_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_MActionPerformed

    public static void showAnimalsInCombo(JComboBox jcombo, int id) throws SQLException{
        
        jcombo.removeAllItems();
        ResultSet rs= getAnimal(id,"proprietaire");
        
        while(rs.next()){
            jcombo.addItem(rs.getString("nomAnimal")+" "+rs.getString("raceAnimal")+" "+rs.getString("especeAnimal")+"_"+rs.getString("idAnimal"));
        }
        
    }
    
    
    private void jCombo_clientItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCombo_clientItemStateChanged
        // TODO add your handling code here:
       String Item  =  jCombo_client.getSelectedItem().toString();
      
       if(jCombo_client.getSelectedIndex()==0){
           try {
               jButton_Ajouter.setEnabled(false);
               resetClientInfo();
               jLabel_notes.setText("veuillez choisir le proprietaire");
               showAnimal(jTable_animal);
               
           } catch (SQLException ex) {
               Logger.getLogger(animalsPanel.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
      else if(!Item.equals(""))
               {
           String[] split = Item.split("_");
           if (split.length >0){
           jButton_Ajouter.setEnabled(true);
           jLabel_notes.setText("");
           String  id    =  split[1] ;
           selectedClient=Integer.parseInt(id);
           System.out.println(id);       
           
           try {
               showClientInfo(Integer.parseInt(id));
               showAnimal(Integer.parseInt(id),jTable_animal);
               
           } catch (SQLException ex) {
               Logger.getLogger(animalsPanel.class.getName()).log(Level.SEVERE, null, ex);
           }
            
           
          
           
           
               } }                   
        
    }//GEN-LAST:event_jCombo_clientItemStateChanged

    private void jText_nomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jText_nomFocusLost
        // TODO add your handling code here:
        String input =jText_nom.getText();
        String regex= "[a-z A-Z]+";
        if (input.matches(regex)){
            
        }
        
    }//GEN-LAST:event_jText_nomFocusLost

    public static void deleteAnimal(int id) throws SQLException{
        String sql="delete from animals where idAnimal="+id;
        Statement stmt =Main.getConnection(Main.jdbc).createStatement();
        stmt.execute(sql);
    }
    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        // TODO add your handling code here:
        String nomAnimal= jText_nom.getText();
        String espece= jText_espece.getText();
        String race = jText_race.getText();
        String sexe = null ;
        String poids =jText_poids.getText();
        String unite =(String) jCombo_unite.getSelectedItem();
        
        String car=jText_car.getText();
        if(  jRadio_F.isSelected()){
          sexe="Female";
      }
        else if(jRadio_M.isSelected()) sexe="Male";
        if(selectedClient==0)  {
            jLabel_notes.setText("veuillez selectionner le proprietaire"); 
            jLabel_name.setText("");
            jLabel_adr.setText("");
            jLabel_mobile.setText("");
            jButton_save.setEnabled(false); }
        else {
            jButton_save.setEnabled(true);
            
            String sql ="update Animals set  "
                    + "nomAnimal ='"+nomAnimal+"'"
                    + ",sexeAnimal ='"+sexe+"'"
                    + ",raceAnimal ='"+race +"'"
                    + ",especeAnimal ='"+espece+"'"
                    + ",carAnimal ='"+car+"'"
                    + ",poids ='"+poids+"'"
                    + ",uniteMesure ='"+unite+"'"
                   +"where idAnimal="+selectedAnimal;
        try {
            Connection connect =Main.getConnection(Main.jdbc);
            
            Statement stmt =connect.createStatement();
            
           boolean execute =stmt.execute(sql);
            if(!execute || execute ){ 
                jLabel_notes.setText("Modification sauvgarder ");
                selectedClient=0;
                selectedAnimal=0;
                showAnimal(jTable_animal);
                
            }
            stmt.close();
            connect.close();
        } catch (SQLException ex) {
            Logger.getLogger(animalsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
    }//GEN-LAST:event_jButton_saveActionPerformed

    private void jPanel_annulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_annulerMouseClicked
        // TODO add your handling code here:
        if(selectedAnimal>0){
            
            try {
                deleteAnimal(selectedAnimal);
                selectedAnimal=-1;
                showAnimal(jTable_animal);
            } catch (SQLException ex) {
                Logger.getLogger(animalsPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        

    }//GEN-LAST:event_jPanel_annulerMouseClicked

    private void jPanel_annulerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_annulerMouseEntered
        mainFrame.hover(jPanel_annuler);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_annulerMouseEntered

    private void jPanel_annulerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_annulerMouseExited
        mainFrame.unhover(jPanel_annuler);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_annulerMouseExited
    public void resetClientInfo(){
                    jLabel_name.setText("");
                    jLabel_adr.setText("");
                    jLabel_mobile.setText("");
    }
    
    public void showClientInfo(int id) throws SQLException{
               ResultSet client = clientPanel.getClient(id);
               while(client.next()){
                           jLabel_name.setText(client.getString("nomclient")+" "+client.getString("prenomClient"));
                           jLabel_adr.setText(client.getString("adrClient"));
                           jLabel_mobile.setText(client.getString("numClient"));
                           
                   
               }
    }
    
    public static ResultSet getAnimal() throws SQLException{
                Connection connect =Main.getConnection(Main.jdbc);
        Statement stmt=connect.createStatement();
        
        String sql="select * from Animals";
        return stmt.executeQuery(sql);
    }
    public void showAnimal(JTable table) throws SQLException{

        
        ResultSet rs = getAnimal();
       DefaultTableModel model = (DefaultTableModel) table.getModel();
       model.setRowCount(0);
       
       while(rs.next()){
           String id=rs.getString("idAnimal");
           String nom=rs.getString("nomAnimal");
           String race=rs.getString("raceAnimal");
           String espece=rs.getString("especeAnimal");
           String sexe=rs.getString("sexeAnimal");
           String car=rs.getString("carAnimal");
           String poids=rs.getString("poids");
           String unite=rs.getString("uniteMesure");
           
           model.insertRow(model.getRowCount(),new Object[]{id,nom,espece,race,sexe,poids+" "+unite});
             }
       rs.close();
    }
    
    public static ResultSet getAnimal(int id,String columnName) throws SQLException{
        Connection connect =Main.getConnection(Main.jdbc);
        Statement stmt=connect.createStatement();
        
        String sql="select * from Animals where "+columnName+"="+id;
        return stmt.executeQuery(sql);
    }
      public void showAnimal(int idClient,JTable table) throws SQLException{
        
        
        ResultSet rs = getAnimal(idClient,"proprietaire");
       DefaultTableModel model = (DefaultTableModel) table.getModel();
       model.setRowCount(0);
       
       while(rs.next()){
           String id=rs.getString("idAnimal");
           String nom=rs.getString("nomAnimal");
           String race=rs.getString("raceAnimal");
           String espece=rs.getString("especeAnimal");
           String sexe=rs.getString("sexeAnimal");
           String car=rs.getString("carAnimal");
           String poids=rs.getString("poids");
           String unite=rs.getString("uniteMesure");
           
           model.insertRow(model.getRowCount(),new Object[]{id,nom,espece,race,sexe,poids+" "+unite});
           
        }
     rs.close();
    }
      private int selectedClient=0;
      private int selectedAnimal=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_sexe;
    private javax.swing.JButton jButton_Ajouter;
    private javax.swing.JButton jButton_save;
    public javax.swing.JComboBox<String> jCombo_client;
    private javax.swing.JComboBox<String> jCombo_unite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_adr;
    private javax.swing.JLabel jLabel_mobile;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_notes;
    private javax.swing.JLabel jLabela;
    private javax.swing.JLabel jLabelm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_annuler;
    private javax.swing.JRadioButton jRadio_F;
    private javax.swing.JRadioButton jRadio_M;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable_animal;
    private javax.swing.JTextArea jText_car;
    private javax.swing.JTextField jText_espece;
    private javax.swing.JTextField jText_nom;
    private javax.swing.JTextField jText_poids;
    private javax.swing.JTextField jText_race;
    // End of variables declaration//GEN-END:variables
}
