/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veto;

import java.awt.Color;
import java.sql.Array;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author AKRAMEE
 */
public class clientPanel extends javax.swing.JPanel {

    /**
     * Creates new form clientPAnel
     */
    
    private int selectedClientID;
    
    public clientPanel() {
        initComponents();
        try {
            showClient();
        } catch (SQLException ex) {
            Logger.getLogger(clientPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        ListSelectionModel model=jTable_Clients.getSelectionModel();
        model.addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
               
                if(! model.isSelectionEmpty()){
                    
                     int  row =model.getMinSelectionIndex();
                        if(row>-1){
                     
                     DefaultTableModel m= (DefaultTableModel) jTable_Clients.getModel();
                   // For midification purpose ;  
                    selectedClientID=Integer.parseInt( m.getValueAt(row, 0).toString());
                    jText_nom.setText(m.getValueAt(row, 1).toString());
                    jText_prenom.setText(m.getValueAt(row, 2).toString());
                    jText_num.setText(m.getValueAt(row, 4).toString());
                    jText_mail.setText((String) m.getValueAt(row, 3).toString());
                    jText_adr1.setText(m.getValueAt(row, 5).toString());
                     jButton_suppClient.setEnabled(true);   
                     
                         try {
                             mainPanel.animal.showAnimal(selectedClientID, jTable_animal);
                         } catch (SQLException ex) {
                             Logger.getLogger(clientPanel.class.getName()).log(Level.SEVERE, null, ex);
                         }
                        
                        }
                     
                    
                    
                    
                }
                
            }
        });
        ListSelectionModel modelAnimal= jTable_animal.getSelectionModel();
        modelAnimal.addListSelectionListener(new ListSelectionListener () {
            @Override
            public void valueChanged(ListSelectionEvent e) {
               DefaultTableModel m= (DefaultTableModel) jTable_animal.getModel();
                if( !modelAnimal.isSelectionEmpty() ){
                    int row= modelAnimal.getMinSelectionIndex();
                    
                    selectedAnimal= Integer.parseInt(""+ m.getValueAt(row,0));
                }
            }
        
        });
       
        jButton_suppClient.setEnabled(false);
    }
    
    
    public void supprimerClient(int id) throws SQLException{
        Connection connect= Main.getConnection(Main.jdbc);
        
        Statement stmt =connect.createStatement();
        String sql="delete from Clients where idClients='"+id+"'";
        
        stmt.execute(sql);
        refreshInput();
        
    }
    public void refreshInput(){
        jText_num.setText("");
        jText_prenom.setText("");
        jText_adr1.setText("");
        jText_nom.setText("");
        jText_mail.setText("");
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jText_nom = new javax.swing.JTextField();
        jText_prenom = new javax.swing.JTextField();
        jText_num = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jText_mail = new javax.swing.JTextField();
        jLabel_notes = new javax.swing.JLabel();
        jButton_suppClient = new javax.swing.JButton();
        jPanel_ajouter1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jText_adr1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_animal = new javax.swing.JTable();
        jPanel_annuler = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel_ajouter = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Clients = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("");
        setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("Nom");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Prenom");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Adresse");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Numero mobile");

        jText_nom.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jText_nom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jText_nomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jText_nomFocusLost(evt);
            }
        });
        jText_nom.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jText_nomCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jText_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_nomActionPerformed(evt);
            }
        });

        jText_prenom.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jText_prenom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jText_prenomFocusLost(evt);
            }
        });
        jText_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_prenomActionPerformed(evt);
            }
        });

        jText_num.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jText_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_numActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Email");

        jText_mail.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jText_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_mailActionPerformed(evt);
            }
        });

        jLabel_notes.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel_notes.setForeground(new java.awt.Color(255, 0, 0));

        jButton_suppClient.setText("Supprimer");
        jButton_suppClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_suppClientActionPerformed(evt);
            }
        });

        jPanel_ajouter1.setBackground(new java.awt.Color(0, 206, 209));
        jPanel_ajouter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_ajouter1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_ajouter1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_ajouter1MouseExited(evt);
            }
        });
        jPanel_ajouter1.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Add New_18px.png"))); // NOI18N
        jLabel12.setText("Ajouter Client");
        jPanel_ajouter1.add(jLabel12, java.awt.BorderLayout.CENTER);

        jText_adr1.setColumns(20);
        jText_adr1.setRows(5);
        jText_adr1.setTabSize(0);
        jText_adr1.setBorder(null);
        jText_adr1.setMinimumSize(new java.awt.Dimension(4, 20));
        jText_adr1.setName(""); // NOI18N
        jText_adr1.setSelectionColor(new java.awt.Color(0, 206, 209));
        jScrollPane3.setViewportView(jText_adr1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jText_mail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jText_num, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jText_nom, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jText_prenom, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel_ajouter1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_suppClient)
                            .addComponent(jLabel_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jText_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jText_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jText_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jText_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jPanel_ajouter1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_suppClient)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));

        jTable_animal.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTable_animal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Espece", "Race", "Sexe", "Poids"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_animal.setSelectionBackground(new java.awt.Color(0, 206, 209));
        jScrollPane2.setViewportView(jTable_animal);
        if (jTable_animal.getColumnModel().getColumnCount() > 0) {
            jTable_animal.getColumnModel().getColumn(0).setMaxWidth(45);
        }

        jPanel_annuler.setBackground(new java.awt.Color(0, 206, 209));
        jPanel_annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_annulerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_annulerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_annulerMouseExited(evt);
            }
        });
        jPanel_annuler.setLayout(new java.awt.BorderLayout());

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Close Window_18px.png"))); // NOI18N
        jLabel10.setText("Supprimer Animal");
        jPanel_annuler.add(jLabel10, java.awt.BorderLayout.CENTER);

        jPanel_ajouter.setBackground(new java.awt.Color(0, 206, 209));
        jPanel_ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_ajouterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_ajouterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_ajouterMouseExited(evt);
            }
        });
        jPanel_ajouter.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Add New_18px.png"))); // NOI18N
        jLabel11.setText("Ajouter Animal");
        jPanel_ajouter.add(jLabel11, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jPanel_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setOpaque(false);

        jTable_Clients.setAutoCreateRowSorter(true);
        jTable_Clients.setBackground(new java.awt.Color(245, 245, 245));
        jTable_Clients.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTable_Clients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nom", "Prenom", "Email", "Mobile", "Adresse"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Clients.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable_Clients.setFillsViewportHeight(true);
        jTable_Clients.setOpaque(false);
        jTable_Clients.setRowHeight(22);
        jTable_Clients.setSelectionBackground(new java.awt.Color(0, 206, 209));
        jScrollPane1.setViewportView(jTable_Clients);
        if (jTable_Clients.getColumnModel().getColumnCount() > 0) {
            jTable_Clients.getColumnModel().getColumn(0).setPreferredWidth(45);
            jTable_Clients.getColumnModel().getColumn(0).setMaxWidth(45);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_annulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_annulerMouseClicked
        // TODO add your handling code here:
        if(selectedAnimal>0){

            try {
                animalsPanel.deleteAnimal(selectedAnimal);
                selectedAnimal=-1;
                mainPanel.animal.showAnimal(jTable_animal);
            } catch (SQLException ex) {
                Logger.getLogger(animalsPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_jPanel_annulerMouseClicked

    private void jPanel_annulerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_annulerMouseEntered
        mainFrame.hover(jPanel_annuler);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_annulerMouseEntered

    private void jPanel_annulerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_annulerMouseExited
        mainFrame.unhover(jPanel_annuler);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_annulerMouseExited

    private void jPanel_ajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterMouseClicked
        // TODO add your handling code here:
        mainFrame.show(mainPanel.animal, "animalsPanel");
    }//GEN-LAST:event_jPanel_ajouterMouseClicked

    private void jPanel_ajouterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterMouseEntered
        // TODO add your handling code here:
        mainFrame.hover(jPanel_ajouter);
    }//GEN-LAST:event_jPanel_ajouterMouseEntered

    private void jPanel_ajouterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterMouseExited
        // TODO add your handling code here:
        mainFrame.unhover(jPanel_ajouter);
    }//GEN-LAST:event_jPanel_ajouterMouseExited

    private void jButton_suppClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_suppClientActionPerformed
        // TODO add your handling code here:
        try{
            supprimerClient(selectedClientID);

            showClient();
            jButton_suppClient.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(clientPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_suppClientActionPerformed

    private void jText_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_mailActionPerformed

    private void jText_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_numActionPerformed

    private void jText_prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_prenomActionPerformed

    private void jText_prenomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jText_prenomFocusLost
        // TODO add your handling code here:
        String value= jText_prenom.getText();
        String regex ="[a-z A-Z]+";
        if(value.equals("")){
            jLabel_notes.setText("Le prenom est obligatoire");
           
        }
        else if( !value.matches(regex)){
            jLabel_notes.setText("Le prenom  est invalide");
            
        }
        else{
            jLabel_notes.setText("");
           
        }
    }//GEN-LAST:event_jText_prenomFocusLost

    private void jText_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_nomActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jText_nomActionPerformed

    private void jText_nomCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jText_nomCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_nomCaretPositionChanged

    private void jText_nomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jText_nomFocusLost
        // TODO add your handling code here:
        String value= jText_nom.getText();
        String regex ="[a-z A-Z]+";
        if(value.equals("")){
            jLabel_notes.setText("Le nom est obligatoire");
            
        }
        else if(!value.matches(regex)){
            jLabel_notes.setText("Le nom est invalide");
            
        }
        else{
            jLabel_notes.setText("");
            
        }
    }//GEN-LAST:event_jText_nomFocusLost

    private void jText_nomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jText_nomFocusGained
        // TODO add your handling code here:
        // la recherche  d'un client avec un nom similaire !!

    }//GEN-LAST:event_jText_nomFocusGained

    private void jPanel_ajouter1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouter1MouseClicked
        // TODO add your handling code here:
         try{
            addClient();

        } catch (SQLException ex) {
            Logger.getLogger(clientPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPanel_ajouter1MouseClicked

    private void jPanel_ajouter1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouter1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_ajouter1MouseEntered

    private void jPanel_ajouter1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouter1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_ajouter1MouseExited

    
    public boolean userExist(String info) throws SQLException{
        Connection connect= Main.getConnection(Main.jdbc);
        
        Statement stmt =connect.createStatement();
        String sql = "SELECT * FROM Clients where Email='"+info+ "'";
                
        
        ResultSet rs= stmt.executeQuery(sql);
        return rs.next() ;
        
    }
    public void getAnimal(int idClient) throws SQLException{
 Connection connect =Main.getConnection(Main.jdbc);
        Statement stmt=connect.createStatement();
        
        String sql="select * from Animals where proprietaire="+idClient;
        
        ResultSet rs = stmt.executeQuery(sql);
       DefaultTableModel model = (DefaultTableModel) jTable_animal.getModel();
       model.setRowCount(0);
       
       while(rs.next()){
           String id=rs.getString("idAnimal");
           String nom=rs.getString("nomAnimal");
           String race=rs.getString("raceAnimal");
           String espece=rs.getString("especeAnimal");
           String sexe=rs.getString("sexeAnimal");
           String car=rs.getString("carAnimal");
           String poids=rs.getString("poids");
           String unite=rs.getString("uniteMesure");
           
           model.insertRow(model.getRowCount(),new Object[]{id,nom,espece,race,sexe,poids+" "+unite});
            
            
            
        }
       stmt.close();
       connect.close();
        
        
        
        
        
    }       
     
    
    public void showClient() throws SQLException{
        
       
        
        ResultSet rs= getClient();

        //printing results into table ;
        DefaultTableModel model = (DefaultTableModel) jTable_Clients.getModel();
        model.setRowCount(0);
        while(rs.next()){
            String id= rs.getString("idclients");
            String nom=rs.getString("nomClient");
            String prenom=rs.getString("prenomClient");
            String email=rs.getString("Email");
            String mobile=rs.getString("numClient");
            String adr=rs.getString("adrClient");
            
            
            model.insertRow(model.getRowCount(), new Object[]{id,nom,prenom,email,mobile,adr});
            
           }
        
        rs.close();
        
        
    }
    
    public void addClient() throws SQLException{
        // getting user input :
        String nom=jText_nom.getText();
        String prenom= jText_prenom.getText();
        String adr =jText_adr1.getText();
        String mobile=jText_num.getText();
        String mail=jText_mail.getText();  
        
        Date date=new Date();
        String naissance;
        
        if(date != null){
            naissance =date.toString();
        }
                

        
        //checking  if this user already exists : 
        if(! mail.equals("") && userExist(mail) ){
            // tell that this user already Exists !
            jLabel_notes.setText(nom+ " "+prenom+" existe deja dans la base de donne");
        }
        else {
            
            // this is a new user :
            
            String sql = "INSERT INTO Clients(`nomClient`,`prenomClient`,`adrClient`,`Email`,`NumClient` )"
                    +"values("
                    +"'"+nom +"',"
                    +"'"+prenom +"',"
                    +"'"+adr +"',"
                    +"'"+mail +"',"
                    +"'"+mobile+"')";

            
            Connection connect= Main.getConnection(Main.jdbc);        
            Statement stmt =connect.createStatement();
            boolean execute = stmt.execute(sql);
            if(execute || !execute ) jLabel_notes.setText("User Added");
            stmt.close();
            connect.close();            
                  }
        
       
        showClient();
        
        showClientInCombo(mainPanel.animal.jCombo_client);
        showClientInCombo(mainPanel.RDV.jCombo_client);
        
        
    }
    
    /**
     *
     * @return
     * @throws SQLException
     */
    

    
    public static ResultSet getClient() throws SQLException{
        Connection connect =Main.getConnection(Main.jdbc);
        Statement stmt= connect.createStatement();
        
        String sql = "select * from Clients";
        return stmt.executeQuery (sql);
    }
    
        public static void showClientInCombo(JComboBox jCombo) throws SQLException{
       
        
        ResultSet rs= clientPanel.getClient();
        
        while(rs.next()){
            String id=rs.getString("idClients");
            String nom=rs.getString("nomClient");
            String prenom =rs.getString("prenomClient");
            
            jCombo.addItem(nom+" "+prenom+ "_"+id);
        }}
    
    public static ResultSet getClient(int idClient) throws SQLException{
        Connection connect =Main.getConnection(Main.jdbc);
        Statement stmt= connect.createStatement();
        
        String sql = "select * from Clients where idClients="+idClient;
        return stmt.executeQuery (sql);
    }
    int selectedAnimal=0;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_suppClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_notes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_ajouter;
    private javax.swing.JPanel jPanel_ajouter1;
    private javax.swing.JPanel jPanel_annuler;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_Clients;
    private javax.swing.JTable jTable_animal;
    private javax.swing.JTextArea jText_adr1;
    private javax.swing.JTextField jText_mail;
    private javax.swing.JTextField jText_nom;
    private javax.swing.JTextField jText_num;
    private javax.swing.JTextField jText_prenom;
    // End of variables declaration//GEN-END:variables
}
