/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veto;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.TableSelectionModel;
import static javafx.scene.input.KeyCode.J;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author AKRAMEE
 */
public class ConsultationPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConsultationPanel
     */
    public ConsultationPanel() {
        date=dtformat.format(new Date());
        
        this.ordonnance = new ArrayList[2];
        this.ordonnance[0]=new ArrayList();
        this.ordonnance[1]= new ArrayList();
        initComponents();
        
          ListSelectionModel model;
            model =jTable_ord.getSelectionModel();
            model.addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    if(!model.isSelectionEmpty())
                        rowOrd = model.getMinSelectionIndex();
                }
            });
        
        try {
            clientPanel.showClientInCombo(jCombo_client);
            medicamentPanel.showMedinJcombo(jCombo_med);
            showConsultationJtable(jTable_cons);
           
          
         
            
        } catch (SQLException ex) {
            Logger.getLogger(ConsultationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jCombo_type = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jText_frais = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jText_notes = new javax.swing.JTextArea();
        jCombo_client = new javax.swing.JComboBox<>();
        jCombo_animal = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel_notes = new javax.swing.JLabel();
        jPanel_validerConsultation = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_cons = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_ord = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel_somme = new javax.swing.JLabel();
        jPanel_ajouterStock1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpin_qte = new com.toedter.components.JSpinField();
        jCombo_med = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel_ajouterStock2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel_ajouterStock3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Information Consultation");

        jCombo_type.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jCombo_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Vaccin", "Chirurgicale" }));
        jCombo_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo_typeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Frais");

        jText_frais.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jText_frais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_fraisActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Notes :");

        jText_notes.setColumns(20);
        jText_notes.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jText_notes.setRows(3);
        jScrollPane1.setViewportView(jText_notes);

        jCombo_client.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jCombo_client.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectioner le client" }));
        jCombo_client.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCombo_clientItemStateChanged(evt);
            }
        });
        jCombo_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo_clientActionPerformed(evt);
            }
        });

        jCombo_animal.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jCombo_animal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectioner le client" }));
        jCombo_animal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCombo_animalItemStateChanged(evt);
            }
        });
        jCombo_animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo_animalActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Client");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setText("Type ");

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setText("Animal");

        jLabel_notes.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel_notes.setForeground(new java.awt.Color(255, 0, 51));

        jPanel_validerConsultation.setBackground(new java.awt.Color(0, 206, 209));
        jPanel_validerConsultation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_validerConsultationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_validerConsultationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_validerConsultationMouseExited(evt);
            }
        });
        jPanel_validerConsultation.setLayout(new java.awt.BorderLayout());

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Add New_18px.png"))); // NOI18N
        jLabel17.setText("Valider");
        jPanel_validerConsultation.add(jLabel17, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCombo_client, javax.swing.GroupLayout.Alignment.TRAILING, 0, 154, Short.MAX_VALUE)
                            .addComponent(jCombo_animal, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCombo_type, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jText_frais, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addGap(44, 44, 44))
                    .addComponent(jLabel_notes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_validerConsultation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jCombo_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jCombo_animal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jCombo_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jText_frais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_validerConsultation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));

        jTable_cons.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTable_cons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Consultation", "Id Animal", "Type", "Prix", "Date", "Heure"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_cons.setRowHeight(22);
        jTable_cons.setRowMargin(2);
        jScrollPane2.setViewportView(jTable_cons);
        if (jTable_cons.getColumnModel().getColumnCount() > 0) {
            jTable_cons.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable_cons.getColumnModel().getColumn(1).setPreferredWidth(40);
        }

        jTable_ord.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTable_ord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicament", "Quantite"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_ord.setRowHeight(22);
        jTable_ord.setRowMargin(2);
        jTable_ord.setSelectionBackground(new java.awt.Color(0, 206, 209));
        jScrollPane3.setViewportView(jTable_ord);

        jLabel_somme.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel_somme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_somme.setText("0 DA");

        jPanel_ajouterStock1.setBackground(new java.awt.Color(0, 206, 209));
        jPanel_ajouterStock1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_ajouterStock1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_ajouterStock1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_ajouterStock1MouseExited(evt);
            }
        });
        jPanel_ajouterStock1.setLayout(new java.awt.BorderLayout());

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Money Bag_24px.png"))); // NOI18N
        jLabel18.setText("Encaisser");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel_ajouterStock1.add(jLabel18, java.awt.BorderLayout.CENTER);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ajouterStock1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_somme, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel_somme, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel_ajouterStock1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(132, Short.MAX_VALUE)))
        );

        jCombo_med.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jCombo_med.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir le medicament" }));
        jCombo_med.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCombo_medItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Prescription");

        jPanel_ajouterStock2.setBackground(new java.awt.Color(0, 206, 209));
        jPanel_ajouterStock2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_ajouterStock2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_ajouterStock2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_ajouterStock2MouseExited(evt);
            }
        });
        jPanel_ajouterStock2.setLayout(new java.awt.BorderLayout());

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Add New_18px.png"))); // NOI18N
        jPanel_ajouterStock2.add(jLabel19, java.awt.BorderLayout.CENTER);

        jPanel_ajouterStock3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel_ajouterStock3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_ajouterStock3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_ajouterStock3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_ajouterStock3MouseExited(evt);
            }
        });
        jPanel_ajouterStock3.setLayout(new java.awt.BorderLayout());

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Cancel_14px.png"))); // NOI18N
        jLabel20.setText("Supprimer");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel_ajouterStock3.add(jLabel20, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCombo_med, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpin_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(120, 120, 120))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator2)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel_ajouterStock2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel_ajouterStock3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2)
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCombo_med, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel_ajouterStock2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSpin_qte, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel_ajouterStock3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jText_fraisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_fraisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_fraisActionPerformed

    private void jCombo_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombo_typeActionPerformed

    private void jCombo_clientItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCombo_clientItemStateChanged
        // TODO add your handling code here:
        String Item  =  jCombo_client.getSelectedItem().toString();

        if(jCombo_client.getSelectedIndex()==0){

            jLabel_notes.setText("veuillez choisir le Client");
            jCombo_animal.removeAllItems();
        }

        else if(!Item.equals(""))
        {
            String[] split = Item.split("_");
            if (split.length >0){

                jLabel_notes.setText("");
                String  id =  split[1] ;
                selectedClient=Integer.parseInt(id);

                System.out.println(id);
                try {
                    animalsPanel.showAnimalsInCombo(jCombo_animal, selectedClient);
                } catch (SQLException ex) {
                    Logger.getLogger(rdvPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            } }
    }//GEN-LAST:event_jCombo_clientItemStateChanged

    private void jCombo_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo_clientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombo_clientActionPerformed

    private void jCombo_animalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCombo_animalItemStateChanged
        // TODO add your handling code here:
        if(jCombo_animal.getSelectedIndex()>0){
            String animal=jCombo_animal.getItemAt(jCombo_animal.getSelectedIndex());
            String[] split =animal.split("_");
            if(split.length>1){
                selectedAnimal=Integer.parseInt(split[1]);
                System.out.println(" "+selectedAnimal);
            }
        }
    }//GEN-LAST:event_jCombo_animalItemStateChanged

    private void jCombo_animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo_animalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombo_animalActionPerformed

    public void addConsultation(int idAnimal, int frais,String type , String note) throws SQLException{
        Statement stmt = Main.getConnection(Main.jdbc).createStatement();
        String sql="insert into ";
        stmt.execute(sql);
    }
    
    public ResultSet getConsultation() throws SQLException{
        
        Statement stmt= Main.getConnection(Main.jdbc).createStatement();
        String sql="select * from consultation";
        return stmt.executeQuery(sql);
    }
    
    public void showConsultationJtable(JTable table) throws SQLException{
        DefaultTableModel model=(DefaultTableModel) table.getModel();
        ResultSet rs=getConsultation();
        model.setRowCount(0);
        while(rs.next()){
            String id=rs.getString("idConsultation");
            String idAnimal=rs.getString("idAnimal");
            String type=rs.getString("type");
            String prix=rs.getString("frais");
            String date=rs.getString("date");
            String heure=rs.getString("heure");
            model.insertRow(model.getRowCount(), new Object[]{
                id,idAnimal,type,prix,date,heure
            });
            
        }
        
    }
    @SuppressWarnings("UnusedAssignment")
    private void jPanel_validerConsultationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_validerConsultationMouseClicked
        // TODO add your handling code here:
            
        
           if(jCombo_client.getSelectedIndex()>=0){
               selectedClient= Integer.parseInt((jCombo_client.getSelectedItem().toString().split("_"))[1]);
                if(jCombo_animal.getSelectedIndex()>=0){
               selectedAnimal= Integer.parseInt((jCombo_animal.getSelectedItem().toString().split("_"))[1]);
                String type= jCombo_type.getSelectedItem().toString();
                String frais= jText_frais.getText();
                String note=jText_notes.getText();
                if(!frais.matches("[0-9]+")){
                    jLabel_notes.setText("veuillez inseer un montant valide");
                }
                else {
                    // Tout  les champs sont valide
                    String sql= "insert into  consultation ( idanimal,date,heure,type,notes,frais) values("
                            + selectedAnimal+","
                            + "strftime('%d-%m-%Y','now'),"
                            + "strftime('%H-%M','now'),'"
                            + type+"','"
                            + note+"',"
                            + frais+")";
                    Statement stmt;
                   try {
                       stmt = Main.getConnection(Main.jdbc).createStatement();
                   boolean execute= stmt.execute(sql);
                           if(execute || ! execute ){
                               jLabel_notes.setText("Sauvgardé");
                               jCombo_type.setSelectedIndex(-1);
                               jCombo_animal.setSelectedIndex(-1);
                               jText_frais.setText("");
                               jText_notes.setText("");
                               showConsultationJtable(jTable_cons);
                               selectedConusltation=Integer.parseInt(jTable_cons.getValueAt(jTable_cons.getRowCount()-1, 0).toString());
                               rowCons=jTable_cons.getRowCount();
                               this.frais=Double.parseDouble(frais);
                               calculer();
                               
                           }
                           
                       
                       
                   } catch (SQLException ex) {
                       Logger.getLogger(ConsultationPanel.class.getName()).log(Level.SEVERE, null, ex);
                   }
                    
                    
                    
                }
                
                }
                else jLabel_notes.setText("Veuiller selectionner l'animal ");
               
           }
           else jLabel_notes.setText("Veuiller selectionner le client ");
          
         
           
       
    }//GEN-LAST:event_jPanel_validerConsultationMouseClicked

    private void jPanel_validerConsultationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_validerConsultationMouseEntered
        // TODO add your handling code here:
        mainFrame.hover(jPanel_validerConsultation);
    }//GEN-LAST:event_jPanel_validerConsultationMouseEntered

    private void jPanel_validerConsultationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_validerConsultationMouseExited
        // TODO add your handling code here:
        mainFrame.unhover(jPanel_validerConsultation);
    }//GEN-LAST:event_jPanel_validerConsultationMouseExited

    private void jCombo_medItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCombo_medItemStateChanged
        String selected;
        if(jCombo_med.getSelectedIndex()>-1){
            selected =jCombo_med.getSelectedItem().toString();
            String[] split =selected.split("_");
            if(split.length>1){
                selectedMed=Integer.parseInt(split [1]);
                System.out.print(selectedMed);
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jCombo_medItemStateChanged

    private void jPanel_ajouterStock1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterStock1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_ajouterStock1MouseClicked

    private void jPanel_ajouterStock1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterStock1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_ajouterStock1MouseEntered

    private void jPanel_ajouterStock1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterStock1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_ajouterStock1MouseExited

    private void jPanel_ajouterStock2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterStock2MouseClicked
        // TODO add your handling code here:
        if(jCombo_med.getSelectedIndex()>-1 && jSpin_qte.getValue()>0){
            int medId= Integer.parseInt(jCombo_med.getSelectedItem().toString().split("_")[1]);
            
            int value =jSpin_qte.getValue();
       DefaultTableModel model=     (DefaultTableModel) jTable_ord.getModel();
       if( ! this.ordonnance[0].contains(medId)){           
            this.ordonnance[0].add(medId); //medicament
            this.ordonnance[1].add(value); // qte 
       
       model.insertRow(model.getRowCount(),new Object []{jCombo_med.getSelectedItem().toString(),value});
            
            System.out.println(medId);
        }
       calculer();
        }
        
        
    }//GEN-LAST:event_jPanel_ajouterStock2MouseClicked

    private void jPanel_ajouterStock2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterStock2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_ajouterStock2MouseEntered

    private void jPanel_ajouterStock2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterStock2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_ajouterStock2MouseExited

    private void jPanel_ajouterStock3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterStock3MouseClicked
        // TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_jPanel_ajouterStock3MouseClicked

    private void jPanel_ajouterStock3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterStock3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_ajouterStock3MouseEntered

    private void jPanel_ajouterStock3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterStock3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_ajouterStock3MouseExited

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        if(rowOrd>=0){
            ((DefaultTableModel)jTable_ord.getModel()).removeRow(rowOrd);
            this.ordonnance[0].remove(rowOrd);
            this.ordonnance[1].remove(rowOrd);
            calculer();
            
        }
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        Double sum=Double.parseDouble( this.jLabel_somme.getText());
       String sql ="insert into caisse(somme,date,type) values("
                + sum+",'"
                + date+"',"
                + "'A')";
        try {
            Main.getConnection(Main.jdbc).createStatement().execute(sql);
        if(  JOptionPane.showConfirmDialog(this.jTable_cons, "Confirmer la reception du "+this.jLabel_somme.getText()+" DA")==0) {
            jLabel_somme.setText("");
            mainPanel.caisse.setCaisse();
        }
        } catch (SQLException ex) {
            Logger.getLogger(ConsultationPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jLabel18MouseClicked
public void calculer(){
     
   Somme=0.0;
    int j=0;
    for(int i=0; i<ordonnance[0].size();i++){
       j= mainPanel.med.medicament[0].indexOf(ordonnance[0].get(i).toString());
       
       Somme+= Double.parseDouble((mainPanel.med.medicament[2].get(j)).toString())* Double.parseDouble(ordonnance[1].get(i).toString());
    }
    Double s=Somme+frais;
    jLabel_somme.setText(""+s);
    
    }

    SimpleDateFormat dtformat= new SimpleDateFormat("dd-MMMM-yyyy");
    String date="";
    int selectedClient=0;
    int selectedConusltation=0;
    int selectedAnimal=0;
    int selectedMed=0;
    int  rowOrd=-1;
    int rowCons=-1;
   Double frais=0.0;
   Double Somme=0.0;
    ArrayList[] ordonnance;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCombo_animal;
    public javax.swing.JComboBox<String> jCombo_client;
    private javax.swing.JComboBox<String> jCombo_med;
    private javax.swing.JComboBox<String> jCombo_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_notes;
    private javax.swing.JLabel jLabel_somme;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_ajouterStock1;
    private javax.swing.JPanel jPanel_ajouterStock2;
    private javax.swing.JPanel jPanel_ajouterStock3;
    private javax.swing.JPanel jPanel_validerConsultation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.toedter.components.JSpinField jSpin_qte;
    private javax.swing.JTable jTable_cons;
    private javax.swing.JTable jTable_ord;
    private javax.swing.JTextField jText_frais;
    private javax.swing.JTextArea jText_notes;
    // End of variables declaration//GEN-END:variables
}
