/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veto;

import java.awt.CardLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Amar
 */
public class mainFrame extends javax.swing.JFrame {

    static void hover(JButton btn) {
               btn.setBackground(new Color(0,153,153));
    }

    static void unhover(JButton btn) {
         btn.setBackground(new Color(0,206,209));
    }

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
         initComponents();        
         
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }         

       
          //IconsPanel.setVisible(false);
          mainPanel mainp= new mainPanel();   
          menuPanel.setVisible(false);
          cl=(CardLayout) panelsPanel.getLayout();
          panelsPanel.add(mainp,"mainPanel");
          this.setLocationRelativeTo(null);
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        IconsPanel = new javax.swing.JPanel();
        homeIcon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rdvIcon = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        clientIcon = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        animalPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        medIcon = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        consultationPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        caisseIcon = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        homeActive = new javax.swing.JPanel();
        RDVActive = new javax.swing.JPanel();
        clientActive = new javax.swing.JPanel();
        animalActive = new javax.swing.JPanel();
        medActive = new javax.swing.JPanel();
        ConsultationActive = new javax.swing.JPanel();
        caisseActive = new javax.swing.JPanel();
        panelsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Cabinet");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        menuPanel.setBackground(new java.awt.Color(0, 206, 209));

        IconsPanel.setBackground(new java.awt.Color(0, 206, 209));
        IconsPanel.setLayout(new java.awt.GridLayout(1, 7, 0, 10));

        homeIcon.setBackground(new java.awt.Color(0, 206, 209));
        homeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeIconMouseExited(evt);
            }
        });
        homeIcon.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Home_56px.png"))); // NOI18N
        homeIcon.add(jLabel2, java.awt.BorderLayout.CENTER);

        IconsPanel.add(homeIcon);

        rdvIcon.setBackground(new java.awt.Color(0, 206, 209));
        rdvIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdvIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rdvIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rdvIconMouseExited(evt);
            }
        });
        rdvIcon.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Schedule_56px.png"))); // NOI18N
        rdvIcon.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Rendez vous");
        rdvIcon.add(jLabel8, java.awt.BorderLayout.PAGE_END);

        IconsPanel.add(rdvIcon);

        clientIcon.setBackground(new java.awt.Color(0, 206, 209));
        clientIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientIconMouseExited(evt);
            }
        });
        clientIcon.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/User Account_56px.png"))); // NOI18N
        clientIcon.add(jLabel3, java.awt.BorderLayout.CENTER);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Clients");
        clientIcon.add(jLabel9, java.awt.BorderLayout.PAGE_END);

        IconsPanel.add(clientIcon);

        animalPanel.setBackground(new java.awt.Color(0, 206, 209));
        animalPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                animalPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                animalPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                animalPanelMouseExited(evt);
            }
        });
        animalPanel.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Dog Paw_56px.png"))); // NOI18N
        animalPanel.add(jLabel6, java.awt.BorderLayout.CENTER);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Animal");
        animalPanel.add(jLabel10, java.awt.BorderLayout.PAGE_END);

        IconsPanel.add(animalPanel);

        medIcon.setBackground(new java.awt.Color(0, 206, 209));
        medIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                medIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                medIconMouseExited(evt);
            }
        });
        medIcon.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Pill_56px.png"))); // NOI18N
        medIcon.add(jLabel4, java.awt.BorderLayout.CENTER);

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Medicament");
        medIcon.add(jLabel11, java.awt.BorderLayout.PAGE_END);

        IconsPanel.add(medIcon);

        consultationPanel.setBackground(new java.awt.Color(0, 206, 209));
        consultationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultationPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultationPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultationPanelMouseExited(evt);
            }
        });
        consultationPanel.setLayout(new java.awt.BorderLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Stethoscope_56px.png"))); // NOI18N
        consultationPanel.add(jLabel7, java.awt.BorderLayout.CENTER);

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Consultation");
        consultationPanel.add(jLabel12, java.awt.BorderLayout.PAGE_END);

        IconsPanel.add(consultationPanel);

        caisseIcon.setBackground(new java.awt.Color(0, 206, 209));
        caisseIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caisseIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                caisseIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                caisseIconMouseExited(evt);
            }
        });
        caisseIcon.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Coins_56px.png"))); // NOI18N
        caisseIcon.add(jLabel5, java.awt.BorderLayout.CENTER);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Caisse");
        caisseIcon.add(jLabel13, java.awt.BorderLayout.PAGE_END);

        IconsPanel.add(caisseIcon);

        jPanel1.setLayout(new java.awt.GridLayout(1, 7));

        homeActive.setBackground(new java.awt.Color(0, 206, 209));

        javax.swing.GroupLayout homeActiveLayout = new javax.swing.GroupLayout(homeActive);
        homeActive.setLayout(homeActiveLayout);
        homeActiveLayout.setHorizontalGroup(
            homeActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        homeActiveLayout.setVerticalGroup(
            homeActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(homeActive);

        RDVActive.setBackground(new java.awt.Color(0, 206, 209));

        javax.swing.GroupLayout RDVActiveLayout = new javax.swing.GroupLayout(RDVActive);
        RDVActive.setLayout(RDVActiveLayout);
        RDVActiveLayout.setHorizontalGroup(
            RDVActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        RDVActiveLayout.setVerticalGroup(
            RDVActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(RDVActive);

        clientActive.setBackground(new java.awt.Color(0, 206, 209));

        javax.swing.GroupLayout clientActiveLayout = new javax.swing.GroupLayout(clientActive);
        clientActive.setLayout(clientActiveLayout);
        clientActiveLayout.setHorizontalGroup(
            clientActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        clientActiveLayout.setVerticalGroup(
            clientActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(clientActive);

        animalActive.setBackground(new java.awt.Color(0, 206, 209));

        javax.swing.GroupLayout animalActiveLayout = new javax.swing.GroupLayout(animalActive);
        animalActive.setLayout(animalActiveLayout);
        animalActiveLayout.setHorizontalGroup(
            animalActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        animalActiveLayout.setVerticalGroup(
            animalActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(animalActive);

        medActive.setBackground(new java.awt.Color(0, 206, 209));

        javax.swing.GroupLayout medActiveLayout = new javax.swing.GroupLayout(medActive);
        medActive.setLayout(medActiveLayout);
        medActiveLayout.setHorizontalGroup(
            medActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        medActiveLayout.setVerticalGroup(
            medActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(medActive);

        ConsultationActive.setBackground(new java.awt.Color(0, 206, 209));

        javax.swing.GroupLayout ConsultationActiveLayout = new javax.swing.GroupLayout(ConsultationActive);
        ConsultationActive.setLayout(ConsultationActiveLayout);
        ConsultationActiveLayout.setHorizontalGroup(
            ConsultationActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        ConsultationActiveLayout.setVerticalGroup(
            ConsultationActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(ConsultationActive);

        caisseActive.setBackground(new java.awt.Color(0, 206, 209));

        javax.swing.GroupLayout caisseActiveLayout = new javax.swing.GroupLayout(caisseActive);
        caisseActive.setLayout(caisseActiveLayout);
        caisseActiveLayout.setHorizontalGroup(
            caisseActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        caisseActiveLayout.setVerticalGroup(
            caisseActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(caisseActive);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(177, 177, 177))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(IconsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        panelsPanel.setBackground(new java.awt.Color(255, 255, 255));
        panelsPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdvIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdvIconMouseEntered
        // TODO add your handling code here:
        hover(rdvIcon);
    }//GEN-LAST:event_rdvIconMouseEntered

    private void homeIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeIconMouseEntered
        // TODO add your handling code here:
        hover(homeIcon);
    }//GEN-LAST:event_homeIconMouseEntered

    private void homeIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeIconMouseExited
        // TODO add your handling code here:
        unhover(homeIcon);
    }//GEN-LAST:event_homeIconMouseExited

    private void rdvIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdvIconMouseExited
        // TODO add your handling code here:
        unhover(rdvIcon);
    }//GEN-LAST:event_rdvIconMouseExited

    private void clientIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientIconMouseEntered
        // TODO add your handling code here:
        hover(clientIcon);
    }//GEN-LAST:event_clientIconMouseEntered

    private void clientIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientIconMouseExited
        // TODO add your handling code here:
        unhover(clientIcon);
    }//GEN-LAST:event_clientIconMouseExited

    private void medIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medIconMouseEntered
        // TODO add your handling code here:
        hover(medIcon);
        
    }//GEN-LAST:event_medIconMouseEntered

    private void medIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medIconMouseExited
        // TODO add your handling code here:
        unhover(medIcon);
        
    }//GEN-LAST:event_medIconMouseExited

    private void caisseIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caisseIconMouseEntered
        // TODO add your handling code here:
        hover(caisseIcon);
    }//GEN-LAST:event_caisseIconMouseEntered

    private void caisseIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caisseIconMouseExited
        // TODO add your handling code here:
        unhover(caisseIcon);
    }//GEN-LAST:event_caisseIconMouseExited

    private void homeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeIconMouseClicked
        // TODO add your handling code here:
        isActive=false;
        menuPanel.setVisible(false);
        cl.show(panelsPanel, "mainPanel");
                       desactivate(this.RDVActive);
        desactivate(this.ConsultationActive);
        desactivate(this.medActive);
        desactivate(this.homeActive);
        desactivate(this.animalActive);
        desactivate(this.caisseActive);
        desactivate(this.clientActive);
    }//GEN-LAST:event_homeIconMouseClicked

    private void clientIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientIconMouseClicked
        // TODO add your handling code here:
        show(mainPanel.client,"clientPanel");
        desactivate(this.RDVActive);
        desactivate(this.ConsultationActive);
        desactivate(this.medActive);
        desactivate(this.homeActive);
        desactivate(this.animalActive);
        desactivate(this.caisseActive);
        activate(this.clientActive);
    }//GEN-LAST:event_clientIconMouseClicked

    private void rdvIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdvIconMouseClicked
        // TODO add your handling code here:
        show(mainPanel.RDV,"rdvPanel");
        activate(this.RDVActive);
        desactivate(this.ConsultationActive);
        desactivate(this.medActive);
        desactivate(this.homeActive);
        desactivate(this.animalActive);
        desactivate(this.caisseActive);
        desactivate(this.clientActive);
    }//GEN-LAST:event_rdvIconMouseClicked

    private void animalPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_animalPanelMouseClicked
        // TODO add your handling code here:
        show(mainPanel.animal,"animalsPanel");
                desactivate(this.RDVActive);
        desactivate(this.ConsultationActive);
        desactivate(this.medActive);
        desactivate(this.homeActive);
        activate(this.animalActive);
        desactivate(this.caisseActive);
        desactivate(this.clientActive);
    }//GEN-LAST:event_animalPanelMouseClicked

    private void animalPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_animalPanelMouseEntered
        // TODO add your handling code here:
        hover(animalPanel);
    }//GEN-LAST:event_animalPanelMouseEntered

    private void animalPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_animalPanelMouseExited
        // TODO add your handling code here:
        unhover(animalPanel);
    }//GEN-LAST:event_animalPanelMouseExited

    private void medIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medIconMouseClicked
        // TODO add your handling code here:
        show(mainPanel.med,"medPanel");
                desactivate(this.RDVActive);
        desactivate(this.ConsultationActive);
        activate(this.medActive);
        desactivate(this.homeActive);
        desactivate(this.animalActive);
        desactivate(this.caisseActive);
        desactivate(this.clientActive);
    }//GEN-LAST:event_medIconMouseClicked

    private void consultationPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultationPanelMouseEntered
        // TODO add your handling code here:
        hover(consultationPanel);
 
    }//GEN-LAST:event_consultationPanelMouseEntered
    public void activate(JPanel p ){
        p.setBackground(new Color(0,153,153));
    }
    public void desactivate(JPanel p){
        p.setBackground(new Color(0,206,209));
    }
    private void consultationPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultationPanelMouseExited
        unhover(consultationPanel);        // TODO add your handling code here:
    }//GEN-LAST:event_consultationPanelMouseExited

    private void consultationPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultationPanelMouseClicked
       show(mainPanel.consultation,"consultation"); 

        desactivate(this.RDVActive);
        activate(this.ConsultationActive);
        desactivate(this.medActive);
        desactivate(this.homeActive);
        desactivate(this.animalActive);
        desactivate(this.caisseActive);
        desactivate(this.clientActive);// TODO add your handling code here:
    }//GEN-LAST:event_consultationPanelMouseClicked

    private void caisseIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caisseIconMouseClicked
    show(mainPanel.caisse,"caisse");   
        desactivate(this.RDVActive);
        desactivate(this.ConsultationActive);
        desactivate(this.medActive);
        desactivate(this.homeActive);
        desactivate(this.animalActive);
        activate(this.caisseActive);
        desactivate(this.clientActive);
    }//GEN-LAST:event_caisseIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
            try{
            Main main = new Main();
            
                } 
            catch (SQLException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
            Login login=new Login();
            

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {


            
            }
        });
    }
    
    
    
    public static void hover (JPanel p){
       
        p.setBackground(new Color(0,153,153));
    }
    public static void unhover( JPanel p){
        
        p.setBackground(new Color(0,206,209));
    }
    public static void active(JPanel p){
        p.setBackground(new Color(0,153,153));
        isActive=true;
    }
    
    public static void show(JPanel panel,String name){
        if(cl!= null){
            panelsPanel.add(panel,name);           
            cl.show(panelsPanel, name);
            menuPanel.setVisible(true);

                        
        }
    }
    
    
    
    private static CardLayout cl ;
    public static boolean isActive=false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConsultationActive;
    private javax.swing.JPanel IconsPanel;
    private javax.swing.JPanel RDVActive;
    private javax.swing.JPanel animalActive;
    private javax.swing.JPanel animalPanel;
    private javax.swing.JPanel caisseActive;
    private static javax.swing.JPanel caisseIcon;
    private javax.swing.JPanel clientActive;
    private static javax.swing.JPanel clientIcon;
    private javax.swing.JPanel consultationPanel;
    private javax.swing.JPanel homeActive;
    private static javax.swing.JPanel homeIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel medActive;
    private static javax.swing.JPanel medIcon;
    private static javax.swing.JPanel menuPanel;
    private static javax.swing.JPanel panelsPanel;
    private static javax.swing.JPanel rdvIcon;
    // End of variables declaration//GEN-END:variables
}
