/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veto;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Amar
 */
public class mainPanel extends javax.swing.JPanel {

    /**
     * Creates new form mainPanel
     */
    public mainPanel() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        rdvPanel = new javax.swing.JPanel();
        rdvIcon = new javax.swing.JLabel();
        rdvText = new javax.swing.JLabel();
        clientPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        animalPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        medPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        consultationPanel = new javax.swing.JPanel();
        rdvText2 = new javax.swing.JLabel();
        rdvIcon2 = new javax.swing.JLabel();
        caissePanel = new javax.swing.JPanel();
        rdvText1 = new javax.swing.JLabel();
        rdvIcon1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridLayout(2, 3, 10, 10));

        rdvPanel.setBackground(new java.awt.Color(245, 245, 245));
        rdvPanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rdvPanelFocusGained(evt);
            }
        });
        rdvPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdvPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rdvPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rdvPanelMouseExited(evt);
            }
        });

        rdvIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Schedule_96px.png"))); // NOI18N

        rdvText.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        rdvText.setForeground(new java.awt.Color(0, 206, 209));
        rdvText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdvText.setText(" Rendez-vous");

        javax.swing.GroupLayout rdvPanelLayout = new javax.swing.GroupLayout(rdvPanel);
        rdvPanel.setLayout(rdvPanelLayout);
        rdvPanelLayout.setHorizontalGroup(
            rdvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rdvPanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(rdvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rdvIcon)
                    .addComponent(rdvText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        rdvPanelLayout.setVerticalGroup(
            rdvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rdvPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdvIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdvText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(rdvPanel);

        clientPanel.setBackground(new java.awt.Color(245, 245, 245));
        clientPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clientPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientPanelMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 206, 209));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Clients");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/User Account_96px.png"))); // NOI18N

        javax.swing.GroupLayout clientPanelLayout = new javax.swing.GroupLayout(clientPanel);
        clientPanel.setLayout(clientPanelLayout);
        clientPanelLayout.setHorizontalGroup(
            clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientPanelLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        clientPanelLayout.setVerticalGroup(
            clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(clientPanel);

        animalPanel.setBackground(new java.awt.Color(245, 245, 245));
        animalPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                animalPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                animalPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                animalPanelMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 206, 209));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Animeaux");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Dog Paw_96px.png"))); // NOI18N

        javax.swing.GroupLayout animalPanelLayout = new javax.swing.GroupLayout(animalPanel);
        animalPanel.setLayout(animalPanelLayout);
        animalPanelLayout.setHorizontalGroup(
            animalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, animalPanelLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(animalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        animalPanelLayout.setVerticalGroup(
            animalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(animalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.add(animalPanel);

        medPanel.setBackground(new java.awt.Color(245, 245, 245));
        medPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                medPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                medPanelMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Pill_96px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 206, 209));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Medicaments");

        javax.swing.GroupLayout medPanelLayout = new javax.swing.GroupLayout(medPanel);
        medPanel.setLayout(medPanelLayout);
        medPanelLayout.setHorizontalGroup(
            medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, medPanelLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        medPanelLayout.setVerticalGroup(
            medPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.add(medPanel);

        consultationPanel.setBackground(new java.awt.Color(245, 245, 245));
        consultationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultationPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultationPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultationPanelMouseExited(evt);
            }
        });

        rdvText2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        rdvText2.setForeground(new java.awt.Color(0, 206, 209));
        rdvText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdvText2.setText("Consultation");

        rdvIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Stethoscope_96px.png"))); // NOI18N

        javax.swing.GroupLayout consultationPanelLayout = new javax.swing.GroupLayout(consultationPanel);
        consultationPanel.setLayout(consultationPanelLayout);
        consultationPanelLayout.setHorizontalGroup(
            consultationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultationPanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(consultationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rdvIcon2)
                    .addComponent(rdvText2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        consultationPanelLayout.setVerticalGroup(
            consultationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdvIcon2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdvText2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(consultationPanel);

        caissePanel.setBackground(new java.awt.Color(245, 245, 245));
        caissePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caissePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                caissePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                caissePanelMouseExited(evt);
            }
        });

        rdvText1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        rdvText1.setForeground(new java.awt.Color(0, 206, 209));
        rdvText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdvText1.setText("Caisse");

        rdvIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Money_96px.png"))); // NOI18N

        javax.swing.GroupLayout caissePanelLayout = new javax.swing.GroupLayout(caissePanel);
        caissePanel.setLayout(caissePanelLayout);
        caissePanelLayout.setHorizontalGroup(
            caissePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caissePanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(caissePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rdvIcon1)
                    .addComponent(rdvText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        caissePanelLayout.setVerticalGroup(
            caissePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caissePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdvIcon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdvText1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(caissePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(195, 195, 195))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(162, 162, 162))
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void setBg(JPanel p){
        p.setBackground(new Color(224,224,224));
    }
    public static void resetBg(JPanel p){
         p.setBackground(new Color(245,245,245));
    }
    private void rdvPanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rdvPanelFocusGained
        // TODO add your handling code here:
        setBg(rdvPanel);
    }//GEN-LAST:event_rdvPanelFocusGained

    private void rdvPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdvPanelMouseEntered
        // TODO add your handling code here:
        setBg(rdvPanel);
    }//GEN-LAST:event_rdvPanelMouseEntered

    private void rdvPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdvPanelMouseExited
        // TODO add your handling code here:
        resetBg(rdvPanel);
    }//GEN-LAST:event_rdvPanelMouseExited

    private void clientPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientPanelMouseEntered
        // TODO add your handling code here:
        setBg(clientPanel);
    }//GEN-LAST:event_clientPanelMouseEntered

    private void clientPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientPanelMouseExited
        // TODO add your handling code here:
        resetBg(clientPanel);
    }//GEN-LAST:event_clientPanelMouseExited

    private void medPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medPanelMouseEntered
        // TODO add your handling code here:
        setBg(medPanel);
        
    }//GEN-LAST:event_medPanelMouseEntered

    private void medPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medPanelMouseExited
        // TODO add your handling code here:
        resetBg(medPanel);
    }//GEN-LAST:event_medPanelMouseExited

    private void caissePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caissePanelMouseEntered
        // TODO add your handling code here:
        setBg(caissePanel);
    }//GEN-LAST:event_caissePanelMouseEntered

    private void caissePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caissePanelMouseExited
        resetBg(caissePanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_caissePanelMouseExited

    private void rdvPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdvPanelMouseClicked
        // TODO add your handling code here:
        mainFrame.show(RDV,"rdvPanel");
        
        
    }//GEN-LAST:event_rdvPanelMouseClicked

    private void clientPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientPanelMouseClicked
        // TODO add your handling code here:
        mainFrame.show(client,"clientPanel");
    }//GEN-LAST:event_clientPanelMouseClicked

    private void animalPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_animalPanelMouseClicked
        // TODO add your handling code here:
        mainFrame.show(animal,"animalsPanel");
    }//GEN-LAST:event_animalPanelMouseClicked

    private void animalPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_animalPanelMouseEntered
        // TODO add your handling code here:
        setBg(animalPanel);
    }//GEN-LAST:event_animalPanelMouseEntered

    private void animalPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_animalPanelMouseExited
        // TODO add your handling code here:
        resetBg(animalPanel);
    }//GEN-LAST:event_animalPanelMouseExited

    private void consultationPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultationPanelMouseEntered
        // TODO add your handling code here:
        setBg(consultationPanel);
    }//GEN-LAST:event_consultationPanelMouseEntered

    private void consultationPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultationPanelMouseExited
        // TODO add your handling code here:
        resetBg(consultationPanel);
    }//GEN-LAST:event_consultationPanelMouseExited

    private void consultationPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultationPanelMouseClicked
        // TODO add your handling code here:
        mainFrame.show(consultation, "ConsPanel");
    }//GEN-LAST:event_consultationPanelMouseClicked

    private void medPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medPanelMouseClicked
        // TODO add your handling code here
        mainFrame.show(med ,"medPanel");
    }//GEN-LAST:event_medPanelMouseClicked

    private void caissePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caissePanelMouseClicked
        // TODO add your handling code here:
        mainFrame.show(caisse,"caisse");
    }//GEN-LAST:event_caissePanelMouseClicked

    /**
     *
     */
    public static rdvPanel RDV = new rdvPanel();
    public static CaissePanel caisse= new CaissePanel();
    public static medicamentPanel med=new medicamentPanel();
    public static clientPanel client= new clientPanel();
    public static animalsPanel animal=new animalsPanel();
    public static ConsultationPanel consultation = new ConsultationPanel(); 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel animalPanel;
    private javax.swing.JPanel caissePanel;
    private javax.swing.JPanel clientPanel;
    private javax.swing.JPanel consultationPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel medPanel;
    private javax.swing.JLabel rdvIcon;
    private javax.swing.JLabel rdvIcon1;
    private javax.swing.JLabel rdvIcon2;
    private javax.swing.JPanel rdvPanel;
    private javax.swing.JLabel rdvText;
    private javax.swing.JLabel rdvText1;
    private javax.swing.JLabel rdvText2;
    // End of variables declaration//GEN-END:variables
}
