/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veto;

import static java.lang.Integer.parseInt;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AKRAMEE
 */
public class medicamentPanel extends javax.swing.JPanel {

    /**
     * Creates new form medicamentPanel
     */
    public medicamentPanel() {
        initComponents();
        medicament = new ArrayList[5];
        medicament[0]= new ArrayList();  // id
        medicament[1]= new ArrayList(); // nom 
        medicament[2]= new ArrayList(); // Prix Vente
        
        try {
            
            showMedinTable();
            showMedinJcombo(jCombo_med);
            
        } catch (SQLException ex) {
            Logger.getLogger(medicamentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch( NullPointerException ex ){
            // do nothing ;
           
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jText_nom = new javax.swing.JTextField();
        jText_achat = new javax.swing.JTextField();
        jText_vente = new javax.swing.JTextField();
        jSpinner_qte = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCombo_med = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDate_F = new com.toedter.calendar.JDateChooser();
        jDate_E = new com.toedter.calendar.JDateChooser();
        jPanel_ajouterStock = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel_ajouter = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jCombo_type = new javax.swing.JComboBox<>();
        jLabel_notes = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_med = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nouveau medicament");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Nom ");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Prix d'achat");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Prix de vente ");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Quantite");

        jText_nom.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jText_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_nomActionPerformed(evt);
            }
        });

        jText_achat.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jText_achat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_achatActionPerformed(evt);
            }
        });

        jText_vente.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jText_vente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_venteActionPerformed(evt);
            }
        });

        jSpinner_qte.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel6.setText("DA/U");

        jLabel7.setText("DA/U");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Type ");

        jCombo_med.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jCombo_med.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir le medicament" }));
        jCombo_med.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCombo_medItemStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Date E");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel11.setText("Date F");

        jDate_F.setBackground(new java.awt.Color(255, 255, 255));
        jDate_F.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jDate_E.setBackground(new java.awt.Color(255, 255, 255));

        jPanel_ajouterStock.setBackground(new java.awt.Color(0, 206, 209));
        jPanel_ajouterStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_ajouterStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_ajouterStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_ajouterStockMouseExited(evt);
            }
        });
        jPanel_ajouterStock.setLayout(new java.awt.BorderLayout());

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Add New_18px.png"))); // NOI18N
        jLabel17.setText("Ajouter au stock");
        jPanel_ajouterStock.add(jLabel17, java.awt.BorderLayout.CENTER);

        jPanel_ajouter.setBackground(new java.awt.Color(0, 206, 209));
        jPanel_ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_ajouterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_ajouterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_ajouterMouseExited(evt);
            }
        });
        jPanel_ajouter.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Add New_18px.png"))); // NOI18N
        jLabel12.setText("Ajouter ");
        jPanel_ajouter.add(jLabel12, java.awt.BorderLayout.CENTER);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Nouvelle Achat");

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setText("Medicament");

        jCombo_type.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jCombo_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comprimes", "Poudre", "Gel", "Injection" }));

        jLabel_notes.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel_notes.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_notes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_ajouterStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(15, 15, 15))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jText_vente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addGap(6, 6, 6))
                                    .addComponent(jSpinner_qte)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jText_achat)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addGap(6, 6, 6))
                                    .addComponent(jDate_F, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jDate_E, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCombo_med, 0, 174, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jPanel_ajouter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel9))
                                        .addGap(70, 70, 70)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jCombo_type, 0, 160, Short.MAX_VALUE)
                                            .addComponent(jText_nom))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(250, 250, 250))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jText_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jCombo_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel14)
                    .addComponent(jCombo_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jDate_F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jDate_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jText_achat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jText_vente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jPanel_ajouterStock, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));

        jTable_med.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTable_med.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Type", "Qte", "Prix d'achat ", "Prix de vente ", "Date Expiration"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_med.setFillsViewportHeight(true);
        jTable_med.setRowHeight(20);
        jTable_med.setSelectionBackground(new java.awt.Color(0, 206, 209));
        jTable_med.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable_med);
        if (jTable_med.getColumnModel().getColumnCount() > 0) {
            jTable_med.getColumnModel().getColumn(0).setMaxWidth(45);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jText_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_nomActionPerformed

    private void jText_achatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_achatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_achatActionPerformed

    private void jText_venteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_venteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_venteActionPerformed
    
    public int ajouterMed(String nom, String type) throws SQLException{
      Statement stmt= Main.getConnection(Main.jdbc).createStatement();
      String sql ="INSERT INTO  MEDICAMENT (nomMedicament, typeMed) values('"
              + nom+"','"
              + type+"')";
       stmt.execute(sql);
       if(stmt.execute("select last_insert_rowid();")){
            selectedMed=Integer.parseInt(stmt.getResultSet().getString("last_insert_rowid()"));
            
            System.out.println(selectedMed+" in adding it");
            
       }
      
      return 0;
        
        
        
    }
    public static ResultSet getMedList() throws SQLException {
        String sql="select * from Medicament";
        Statement stmt =Main.getConnection(Main.jdbc).createStatement();
        return stmt.executeQuery(sql);
    }
    public static void showMedinJcombo(JComboBox combo ) throws SQLException{
        ResultSet rs= getMedList();
        
        combo.removeAllItems();
        while(rs.next())  {
            combo.addItem(rs.getString("nomMedicament")+" _"+rs.getString("idMedicament"));
        }
        
        
    }
    public ResultSet getMed() throws SQLException{
        String sql = "SELECT Medicament.idmedicament,nomMedicament,typeMed,qte, prixAchat, prixvente, dateE from Medicament "
                + "inner join gestMedicament on Medicament.idMedicament = gestMedicament.idMedicament ";
        Statement stmt =Main.getConnection(Main.jdbc).createStatement();
        return stmt.executeQuery(sql);
    }
    public void showMedinTable() throws SQLException{
        ResultSet rs=getMed();
        DefaultTableModel model=(DefaultTableModel) jTable_med.getModel();
        model.setRowCount(0);
        
             String id;        
             String nom;       
             String type;        
             String qte;      
             String pachat;        
             String pvente;        
             String dateE;
           
        
        while(rs.next()){
            id = rs.getString("idmedicament");
            medicament[0].add(id);
            nom = rs.getString("nomMedicament");
            medicament[1].add(nom);
            type = rs.getString("typeMed");
            qte = rs.getString("qte");
            pachat = rs.getString("prixAchat"); 
            medicament[2].add(pachat);
            pvente = rs.getString("prixvente");
            dateE = rs.getString("dateE");
            if(Integer.parseInt(qte)>0){
            model.insertRow(model.getRowCount(),new Object []{
                id,nom,type,qte,pachat,pvente,dateE
                
            }
            );
            }            
        }
        
        
    }
    
    private void jPanel_ajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterMouseClicked
        // TODO add your handling code here:
        String nom = jText_nom.getText();
        String type= jCombo_type.getSelectedItem().toString();
        if(nom!="" && type!=""){
            try {
                
                ajouterMed(nom,type);
                showMedinJcombo(jCombo_med);                
                jCombo_med.setSelectedItem(nom+"_"+selectedMed);
                System.out.println(selectedMed);
                showMedinTable();
                Object valueAt = jTable_med.getValueAt(jTable_med.getRowCount()-1,0);
                
                jCombo_med.setSelectedItem(nom+"_"+selectedMed);
                
            } catch (SQLException ex) {
                Logger.getLogger(medicamentPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        

    }//GEN-LAST:event_jPanel_ajouterMouseClicked

    private void jPanel_ajouterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterMouseEntered
        mainFrame.hover(jPanel_ajouter);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_ajouterMouseEntered

    private void jPanel_ajouterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterMouseExited
        mainFrame.unhover(jPanel_ajouter);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_ajouterMouseExited

    private void jPanel_ajouterStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterStockMouseClicked
        // TODO add your handling code here:
        
            SimpleDateFormat dtformat= new SimpleDateFormat("dd-MMMM-yyyy");
            String dateE="";
            String dateF="";
            String prixAchat="";
            String prixVente="";
            String qte=jSpinner_qte.getValue().toString();
            
            if(jDate_E.getDate()!=null)
                dateE= dtformat.format(jDate_E.getDate());
            if(jDate_F.getDate()!=null)
                dateF= dtformat.format(jDate_F.getDate());
            String today=dtformat.format(new Date());
            prixAchat=jText_achat.getText();
            prixVente=jText_vente.getText();
            
            
            if(selectedMed>0 && dateF!="" && dateE!="" && prixVente!="" && Integer.parseInt(qte)>0){
                jLabel_notes.setText("");
                String sql="insert into gestMedicament(idMedicament,qte,prixAchat,prixVente,dateAchat,dateE,dateF) values("
                        + selectedMed+","
                        + "'"+qte+"',"
                        + "'"+prixAchat+"',"
                                + "'"+prixVente+"',"
                                + "'"+today+"',"
                                + "'"+dateE+"',"
                                + "'"+dateF+"')";
                Statement stmt;
                try {
                    stmt = Main.getConnection(Main.jdbc).createStatement();
                     stmt.execute(sql);
                     showMedinTable();
                } catch (SQLException ex) {
                    Logger.getLogger(medicamentPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
               
                
                
                
            }
            else {
                jLabel_notes.setText("veuillez remplir tout les champs");
            }
    }//GEN-LAST:event_jPanel_ajouterStockMouseClicked

    private void jPanel_ajouterStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterStockMouseEntered
        // TODO add your handling code here:
        mainFrame.hover(jPanel_ajouterStock);
    }//GEN-LAST:event_jPanel_ajouterStockMouseEntered

    private void jPanel_ajouterStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ajouterStockMouseExited
        // TODO add your handling code here:
        mainFrame.unhover(jPanel_ajouterStock);
    }//GEN-LAST:event_jPanel_ajouterStockMouseExited

    private void jCombo_medItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCombo_medItemStateChanged
    String selected;
        if(jCombo_med.getSelectedIndex()>-1){
         selected =jCombo_med.getSelectedItem().toString();
         String[] split =selected.split("_");
         if(split.length>1){
             selectedMed=Integer.parseInt(split [1]);
             System.out.print(selectedMed);
         }
         
        }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombo_medItemStateChanged


    int selectedMed=0;
    ArrayList medicament[];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCombo_med;
    private javax.swing.JComboBox<String> jCombo_type;
    private com.toedter.calendar.JDateChooser jDate_E;
    private com.toedter.calendar.JDateChooser jDate_F;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_notes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_ajouter;
    private javax.swing.JPanel jPanel_ajouterStock;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner_qte;
    private javax.swing.JTable jTable_med;
    private javax.swing.JTextField jText_achat;
    private javax.swing.JTextField jText_nom;
    private javax.swing.JTextField jText_vente;
    // End of variables declaration//GEN-END:variables
}
