/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veto;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amar
 */
public class rdvPanel extends javax.swing.JPanel {

    /**
     * Creates new form rdvPanel
     */
    public rdvPanel() {
        initComponents();
       
        
        try {
            clientPanel.showClientInCombo(jCombo_client);
            showRDVinjTable();
           ListSelectionModel model=jTable_RDV.getSelectionModel();
           model.addListSelectionListener(new ListSelectionListener(){
                @Override
                public void valueChanged(ListSelectionEvent e) {
                 int row ;
                 DefaultTableModel m=(DefaultTableModel) jTable_RDV.getModel();
                 
                 if( model.isSelectionEmpty()){
                     selectedRDV=0;
                 }
                 else {
                     row=model.getMinSelectionIndex();
                     selectedRDV=Integer.parseInt((String) m.getValueAt(row, 0));
                 }
                    
                    
                }
            }
           );
            
            
          
        } catch (SQLException ex) {
            Logger.getLogger(rdvPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_type = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_RDV = new javax.swing.JTable();
        jPanel_consult = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel_annuler = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jCombo_client = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jCombo_animal = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jDate_date = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jText_heure = new javax.swing.JTextField();
        jRadio_interne = new javax.swing.JRadioButton();
        jRadio_externe = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jText_adr = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel_notes = new javax.swing.JLabel();
        jPanel_Ajouter = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jScrollPane1.setBorder(null);

        jTable_RDV.setAutoCreateRowSorter(true);
        jTable_RDV.setBackground(new java.awt.Color(245, 245, 245));
        jTable_RDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Date", "Client", "Type", "Adresse"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_RDV.setToolTipText("");
        jTable_RDV.setFillsViewportHeight(true);
        jTable_RDV.setRowHeight(24);
        jTable_RDV.setRowMargin(2);
        jTable_RDV.setSelectionBackground(new java.awt.Color(0, 206, 209));
        jScrollPane1.setViewportView(jTable_RDV);
        if (jTable_RDV.getColumnModel().getColumnCount() > 0) {
            jTable_RDV.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jPanel_consult.setBackground(new java.awt.Color(0, 206, 209));
        jPanel_consult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_consultMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_consultMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_consultMouseExited(evt);
            }
        });
        jPanel_consult.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Tick Box_18px.png"))); // NOI18N
        jLabel7.setText("Consulter");
        jPanel_consult.add(jLabel7, java.awt.BorderLayout.CENTER);

        jPanel_annuler.setBackground(new java.awt.Color(0, 206, 209));
        jPanel_annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_annulerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_annulerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_annulerMouseExited(evt);
            }
        });
        jPanel_annuler.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Close Window_18px.png"))); // NOI18N
        jLabel8.setText("Annuler RDV ");
        jPanel_annuler.add(jLabel8, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_consult, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_annuler, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jPanel_consult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(245, 245, 245));

        jCombo_client.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jCombo_client.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectioner le client" }));
        jCombo_client.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCombo_clientItemStateChanged(evt);
            }
        });
        jCombo_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo_clientActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("Client");

        jCombo_animal.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jCombo_animal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectioner le client" }));
        jCombo_animal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCombo_animalItemStateChanged(evt);
            }
        });
        jCombo_animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo_animalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Animal");

        jDate_date.setDateFormatString("dd MMM yyyy");
        jDate_date.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jDate_date.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Date");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Heure");

        jText_heure.setSelectionColor(new java.awt.Color(0, 206, 209));
        jText_heure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_heureActionPerformed(evt);
            }
        });

        buttonGroup_type.add(jRadio_interne);
        jRadio_interne.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jRadio_interne.setSelected(true);
        jRadio_interne.setText("Interene");

        buttonGroup_type.add(jRadio_externe);
        jRadio_externe.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jRadio_externe.setText("Externe");
        jRadio_externe.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadio_externeStateChanged(evt);
            }
        });
        jRadio_externe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_externeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Type");

        jText_adr.setColumns(14);
        jText_adr.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jText_adr.setRows(3);
        jText_adr.setBorder(null);
        jText_adr.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jText_adr.setEnabled(false);
        jText_adr.setSelectionColor(new java.awt.Color(0, 206, 209));
        jScrollPane2.setViewportView(jText_adr);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Adresse");

        jLabel_notes.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel_notes.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_notes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel_Ajouter.setBackground(new java.awt.Color(0, 206, 209));
        jPanel_Ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_AjouterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_AjouterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_AjouterMouseExited(evt);
            }
        });
        jPanel_Ajouter.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veto/Add New_18px.png"))); // NOI18N
        jLabel9.setText("Ajouter RDV");
        jPanel_Ajouter.add(jLabel9, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jDate_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCombo_animal, javax.swing.GroupLayout.Alignment.LEADING, 0, 177, Short.MAX_VALUE)
                                    .addComponent(jCombo_client, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jText_heure))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jRadio_interne)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadio_externe)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_notes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_Ajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCombo_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCombo_animal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jDate_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jText_heure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadio_interne)
                            .addComponent(jRadio_externe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadio_externeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_externeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_externeActionPerformed

    private void jRadio_externeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadio_externeStateChanged
        // TODO add your handling code here:
        if(jRadio_externe.isSelected()){
            jText_adr.setEnabled(true);
        }
        else jText_adr.setEnabled(false);
    }//GEN-LAST:event_jRadio_externeStateChanged

    private void jText_heureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_heureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_heureActionPerformed

    private void jCombo_animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo_animalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombo_animalActionPerformed

    private void jCombo_animalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCombo_animalItemStateChanged
        // TODO add your handling code here:
        if(jCombo_animal.getSelectedIndex()>0){
            String animal=jCombo_animal.getItemAt(jCombo_animal.getSelectedIndex());
            String[] split =animal.split("_");
            if(split.length>1){
                selectedAnimal=Integer.parseInt(split[1]);
                System.out.println(" "+selectedAnimal);
            }
        }
    }//GEN-LAST:event_jCombo_animalItemStateChanged

    private void jCombo_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombo_clientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombo_clientActionPerformed

    private void jCombo_clientItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCombo_clientItemStateChanged
        // TODO add your handling code here:
        String Item  =  jCombo_client.getSelectedItem().toString();

        if(jCombo_client.getSelectedIndex()==0){
            
            jLabel_notes.setText("veuillez choisir le Client");
            jCombo_animal.removeAllItems();
        }

        else if(!Item.equals(""))
        {
            String[] split = Item.split("_");
            if (split.length >0){
                
                jLabel_notes.setText("");
                String  id =  split[1] ;
                selectedClient=Integer.parseInt(id);

                System.out.println(id);
                try {
                    animalsPanel.showAnimalsInCombo(jCombo_animal, selectedClient);
                } catch (SQLException ex) {
                    Logger.getLogger(rdvPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            } }

    }//GEN-LAST:event_jCombo_clientItemStateChanged

    private void jPanel_consultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_consultMouseEntered
        // TODO add your handling code here:
        mainFrame.hover(jPanel_consult);
    }//GEN-LAST:event_jPanel_consultMouseEntered

    private void jPanel_consultMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_consultMouseExited
mainFrame.unhover(jPanel_consult);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_consultMouseExited

    private void jPanel_annulerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_annulerMouseEntered
mainFrame.hover(jPanel_annuler);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_annulerMouseEntered

    private void jPanel_annulerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_annulerMouseExited
mainFrame.unhover(jPanel_annuler);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_annulerMouseExited

    private void jPanel_consultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_consultMouseClicked
        // TODO add your handling code here:
        
        //Consult if selecctedRDV >0
        if(selectedRDV>0){
            /* Consulter*/
        }
    }//GEN-LAST:event_jPanel_consultMouseClicked

    private void jPanel_annulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_annulerMouseClicked
        // TODO add your handling code here:
        if(selectedRDV>0){
            System.out.println(""+selectedRDV);
            String sql = "delete from rdv where idRDV ="+selectedRDV;
            Statement stmt;
            try {
                stmt = Main.getConnection(Main.jdbc).createStatement();        
                stmt.execute(sql);
                jLabel_notes.setText("Deleted");
                selectedRDV=0;
                showRDVinjTable();
            } catch (SQLException ex) {
                Logger.getLogger(rdvPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jPanel_annulerMouseClicked

    private void jPanel_AjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_AjouterMouseClicked
        // TODO add your handling code here:
        if(jCombo_client.getSelectedIndex()<=0){

            jLabel_notes.setText("veuillez selectionnez le client Sinon Ajouter un ");

        }
        else {
            SimpleDateFormat dtformat= new SimpleDateFormat("dd-MMMM-yyyy");
            String date="";
            if(jDate_date.getDate()!=null)
            date= dtformat.format(jDate_date.getDate());

            String type=jRadio_interne.isSelected() ?"interne": "externe";
            String adr=jText_adr.getText();
            String sql="insert into RDV ("
            + "idClient,"
            + "date,"
            + "typeRdv,"
            + "Adresse,idAnimal)"
            + "values("
            + selectedClient+","
            + "'"+date+"',"
            + "'"+type+"',"
            + "'"+adr+"',";

            if(selectedAnimal!=0){
                sql+="'"+selectedAnimal+"')";

            }
            else sql+="NULL)";

            try {

                Connection connect =Main.getConnection(Main.jdbc);

                Statement stmt =connect.createStatement();

                boolean execute =stmt.execute(sql);
                if(!execute || execute ){
                    jLabel_notes.setText("Rendez-vous ajouté ");
                    selectedClient=0;
                    selectedAnimal=0;
                    showRDVinjTable();
                }}
                catch (SQLException ex) {
                    Logger.getLogger(rdvPanel.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        
    }//GEN-LAST:event_jPanel_AjouterMouseClicked

    private void jPanel_AjouterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_AjouterMouseEntered
        // TODO add your handling code here:
        mainFrame.hover(jPanel_Ajouter);
    }//GEN-LAST:event_jPanel_AjouterMouseEntered

    private void jPanel_AjouterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_AjouterMouseExited
        // TODO add your handling code here:
        mainFrame.unhover(jPanel_Ajouter);
    }//GEN-LAST:event_jPanel_AjouterMouseExited
    public ResultSet getRDV() throws SQLException {
       
        String sql="select idRDV,idClient,idAnimal,nomClient,prenomClient,typeRdv,Adresse,date from RDV inner join Clients on Clients.idClients=RDV.idClient";
        Statement stmt= Main.getConnection(Main.jdbc).createStatement();
         return stmt.executeQuery(sql);
    }
    public void showRDVinjTable() throws SQLException{
        
        DefaultTableModel model=(DefaultTableModel) jTable_RDV.getModel();
        
        ResultSet rs=getRDV();
        model.setRowCount(0);
        while(rs.next()){
            model.addRow(new Object[]{rs.getString("idRdv")
                                ,     rs.getString("date")
                                ,     rs.getString("nomClient")+ " "+rs.getString("prenomClient")
                                ,     rs.getString("typeRDV")
                                ,      rs.getString("adresse")
            }
            );
            
            
        }
        
        
    }
    
    
    private int selectedClient=0;
    private int selectedAnimal=0;
    private int selectedRDV=0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_type;
    private javax.swing.JComboBox<String> jCombo_animal;
    public javax.swing.JComboBox<String> jCombo_client;
    private com.toedter.calendar.JDateChooser jDate_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_notes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_Ajouter;
    private javax.swing.JPanel jPanel_annuler;
    private javax.swing.JPanel jPanel_consult;
    private javax.swing.JRadioButton jRadio_externe;
    private javax.swing.JRadioButton jRadio_interne;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_RDV;
    private javax.swing.JTextArea jText_adr;
    private javax.swing.JTextField jText_heure;
    // End of variables declaration//GEN-END:variables
}
